name: github_search
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  url_launcher: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.1

flutter:
  uses-material-design: true
